# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4f1d17a13673b1830bae027a6b064981c34daf6279699c99790c27dd4416b9da637259d4675cd530032c42ac348e5e7f1b0e2e3c2322806f19e424d1f7aea7a
  slack_incomingwebhook_url: "https://hooks.slack.com/services/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"
  slack_outgoingwebhook_token: "AMujp6sOjmJzQRsZlMt2GlQf"

test:
  secret_key_base: 7d41fbad41427385c5468ab4b44fc40e2b6039c830bc0d78ed68d8603bb8275a601689bdc8712105b10b143fd9711e9185ef6002947fbdb74daa6e218936faab
  slack_incomingwebhook_url: "https://hooks.slack.com/services/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"
  slack_outgoingwebhook_token: "AMujp6sOjmJzQRsZlMt2GlQf"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  slack_incomingwebhook_url: "https://hooks.slack.com/services/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"
  slack_outgoingwebhook_token: "AMujp6sOjmJzQRsZlMt2GlQf"
